// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"
	agents "go-drop-logistik/modules/agents"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// CheckByID provides a mock function with given fields: ctx, id
func (_m *Repository) CheckByID(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *Repository) Delete(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: ctx, start, last
func (_m *Repository) Fetch(ctx context.Context, start int, last int) ([]agents.Domain, int, error) {
	ret := _m.Called(ctx, start, last)

	var r0 []agents.Domain
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []agents.Domain); ok {
		r0 = rf(ctx, start, last)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]agents.Domain)
		}
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(context.Context, int, int) int); ok {
		r1 = rf(ctx, start, last)
	} else {
		r1 = ret.Get(1).(int)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = rf(ctx, start, last)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetByEmail provides a mock function with given fields: ctx, email
func (_m *Repository) GetByEmail(ctx context.Context, email string) (agents.ExistingDomain, error) {
	ret := _m.Called(ctx, email)

	var r0 agents.ExistingDomain
	if rf, ok := ret.Get(0).(func(context.Context, string) agents.ExistingDomain); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(agents.ExistingDomain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *Repository) GetByID(ctx context.Context, id int) (agents.Domain, error) {
	ret := _m.Called(ctx, id)

	var r0 agents.Domain
	if rf, ok := ret.Get(0).(func(context.Context, int) agents.Domain); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(agents.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: ctx, data
func (_m *Repository) Register(ctx context.Context, data *agents.Domain) error {
	ret := _m.Called(ctx, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *agents.Domain) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, data, id
func (_m *Repository) Update(ctx context.Context, data *agents.Domain, id int) error {
	ret := _m.Called(ctx, data, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *agents.Domain, int) error); ok {
		r0 = rf(ctx, data, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
