app:
  env: ""
  debug: false
  version: 1.0.0
server:
  address: 8000
  timeout: 2
mysql:
  host: "localhost"
  port: ""
  user: ""
  pass: ""
  name: ""
mongo:
  host: "localhost"
  port: ""
  user: ""
  pass: ""
  name: ""
jwt:
  secret: ""
  expired: 1
