app:
  env: "DEV"
  debug: true
  version: 1.0.0
server:
  address: 8000
  timeout: 2
mysql:
  host: "localhost"
  port: ""
  user: ""
  pass: ""
  name: ""
mongo:
  host: "localhost"
  port: ""
  user: ""
  pass: ""
  name: ""
postgres:
  host: "localhost"
  port: "5432"
  user: "postgres"
  pass: "admin"
  name: "go-drop-logistik"
jwt:
  secret: "supersecret12345!@#$%"
  expired: 1
