// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"
	users "go-drop-logistik/modules/users"

	mock "github.com/stretchr/testify/mock"
)

// Usecase is an autogenerated mock type for the Usecase type
type Usecase struct {
	mock.Mock
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *Usecase) GetByID(ctx context.Context, id int) (users.Domain, error) {
	ret := _m.Called(ctx, id)

	var r0 users.Domain
	if rf, ok := ret.Get(0).(func(context.Context, int) users.Domain); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(users.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mock function with given fields: ctx, email, password, sso
func (_m *Usecase) Login(ctx context.Context, email string, password string, sso bool) (string, error) {
	ret := _m.Called(ctx, email, password, sso)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) string); ok {
		r0 = rf(ctx, email, password, sso)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string, bool) error); ok {
		r1 = rf(ctx, email, password, sso)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: ctx, data, sso
func (_m *Usecase) Register(ctx context.Context, data *users.Domain, sso bool) error {
	ret := _m.Called(ctx, data, sso)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *users.Domain, bool) error); ok {
		r0 = rf(ctx, data, sso)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
