swagger: "2.0"
info:
  version: 1.0.0
  title: Go-Drop-Logistik API
definitions:

  # General Parameter
  general.Tracking:
    properties:
      receipt_code:
        type: string
        description: Tracking Code
        example: "INV123456789"
    required: [receipt_code]
    type: object

  # Admins Parameter
  admins.ReqLogin:
    properties:
      email:
        type: string
        description: Email
        example: "admin@gmail.com"
      password:
        type: string
        description: Password
        example: "admin"
    required:
      - email
      - password
    type: object

  # Admins Response
  admins.ResLogin:
    $ref: '#/definitions/helpers.JSONResponse'

  # Helpers
  helpers.JSONResponse:
    properties:
      meta:
        type: object
        properties: 
          message:
            type: string
      data:
        type: object
    type: object


paths:
  # GENERAL
  /tracking:
    post:
      consumes:
        - application/json
      description:
        "Get tracking data"
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/helpers.JSONResponse"
      produces:
        - application/json
      parameters:
        - description: Body
          in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/general.Tracking"
      summary:
        "Tracking package"
      tags:
          - General
  
  # ADMINS
  /admin/login:
    post:
      consumes:
        - application/json
      description:
        "Login admin"
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/helpers.JSONResponse"
            example:
              meta:
                message: "success"
              data:
                access_token: "access_token"
                refresh_token: "refresh_token" 
      produces:
        - application/json
      parameters:
        - description: Body
          in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/admins.ReqLogin"
      summary:
        "Login admin"
      tags:
          - General

securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Token-app
    type: apiKey
