openapi: "3.0.0"
info:
  version: 1.0.0
  title: Go-Drop-Logistik API
components:
  # General Parameter
  schemas:
    General.Tracking:
      properties:
        receipt_code:
          type: string
          description: Tracking Code
          example: "INV123456789"
      required: [receipt_code]
      type: object

    # Admins Parameter
    admins.ReqLogin:
      properties:
        email:
          type: string
          description: Email
          example: "admin@gmail.com"
        password:
          type: string
          description: Password
          example: "admin"
      required:
        - email
        - password
      type: object

    # Users Parameter
    users.ReqLogin:
      properties:
        email:
          type: string
          description: Email
          example: "user@gmail.com"
        password:
          type: string
          description: Password
          example: "user"
      required:
        - email
        - password
      type: object

    # Agents Parameter
    agent.ReqLogin:
      properties:
        email:
          type: string
          description: Email
          example: "agent@gmail.com"
        password:
          type: string
          description: Password
          example: "agent"
      required:
        - email
        - password
      type: object

    # Helpers
    helpers.JSONResponse:
      properties:
        meta:
          type: object
          properties:
            message:
              type: string
        data:
          type: object
      type: object

  examples:
    # Admins Response
    ResLogin:
      value:
        meta:
          message: "success"
        data:
          access_token: "c18ff11b7c6329f4fe2aca5e5191d6af108cfe9a34630464543bb8d77bad9f822fe69e10c3662f2f84df4ebd21a66602dde03f32f66bc72ad324a296b70d582d"
          refresh_token: "1e9c6653d447d54c0de80c45ad0e72e762da4e7040a9047d3177ae99fd0778666e9e9c88021532024b2ed35205396ffde64b7f58c444a74b32dd6c01db57e55a"

paths:
  # GENERAL
  /tracking:
    post:
      description: "Get tracking data"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/General.Tracking"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/helpers.JSONResponse"
      summary: "Tracking package"
      tags:
        - General

  # ADMINS
  /admin/login:
    post:
      description: "Login admin"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/helpers.JSONResponse"
              examples:
                admins.ResLogin:
                  $ref: "#/components/examples/ResLogin"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/admins.ReqLogin"
      summary: "Login admin"
      tags:
        - Admins

  /agent/login:
    post:
      description: "Login agent"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/helpers.JSONResponse"
              examples:
                admins.ResLogin:
                  $ref: "#/components/examples/ResLogin"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/agent.ReqLogin"
      summary: "Login agent"
      tags:
        - Agents

  # USERS
  /login:
    post:
      description: "Login user"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/helpers.JSONResponse"
              examples:
                admins.ResLogin:
                  $ref: "#/components/examples/ResLogin"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/users.ReqLogin"
      summary: "Login user"
      tags:
        - Users
