name: Go

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:

  testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Running unit testing
      run: go test ./... -failfast -cover -coverpkg=./... -coverprofile=coverage.out && go tool cover -html=coverage.out -o cover.html