name: Go

on:
  push:
    branches: 
      - dev
      - master
  pull_request:
    branches: [ dev ]

jobs:
  build-service:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Running unit testing
        run: go test -v ./... -failfast -cover -coverpkg=./... -coverprofile=coverage.out && go tool cover -html=coverage.out -o cover.html
      - name: Upload Coverage report to CodeCov
        uses: codecov/codecov-action@v1.0.0
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: coverage.out
      - name: Running migration database
        run: go run cmd/migrations/migrations.go go-drop-logistik:migrate --up